[project]
name = "pyrigs"
version = "0.1.0"
description = "A Django-based event booking system designed for use by TEC PA and Lighting"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "beautifulsoup4~=4.14",
    "Brotli~=1.2",
    "Django~=5.2",
    "django-ical~=1.9",
    "django-registration-redux~=2.13",
    "django-reversion~=6.0",
    "django-widget-tweaks~=1.5",
    "django-htmlmin~=0.11",
    "envparse~=0.2",
    "gunicorn~=26.1",
    "Markdown~=3.9",
    "Pillow~=12.3",
    "premailer~=3.10",
    "psycopg2-binary~=2.9",
    "pypdf~=6.19",
    "pytz~=2025.2",
    "reportlab~=4.4",
    "simplejson~=3.20",
    "whitenoise~=6.12",
    "sentry-sdk~=2.68",
    "diff-match-patch>=20241021,<20300000",
    "python-barcode~=0.16",
    "django-hcaptcha~=0.2",
    "z3c.rml~=5.0",
    "django-queryable-properties~=1.12",
    "django-mass-edit~=3.5",
]

[dependency-groups]
dev = [
    "pycodestyle~=2.14",
    "coveralls~=4.0",
    "django-coverage-plugin~=3.1",
    "pytest-cov~=7.1",
    "pytest-django~=4.14",
    "pytest~=9.1",
    "selenium~=4.35",
    "pytest-reverse~=1.9",
    "pytest-xdist[psutil]~=3.8",
    "autopep8~=2.3",
    "pip-audit~=2.10",
]
