[project]
name = "pyrigs"
version = "0.1.0"
description = "A Django-based event booking system designed for use by TEC PA and Lighting"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "asgiref",
    "beautifulsoup4",
    "Brotli",
    "dj-database-url",
    "dj-static",
    "Django~=5.2",
    "django-filter",
    "django-ical",
    "django-recurrence",
    "django-registration-redux",
    "django-reversion",
    "django-widget-tweaks",
    "django-htmlmin",
    "envparse",
    "gunicorn",
    "icalendar",
    "Markdown",
    "Pillow",
    "premailer",
    "psutil",
    "psycopg2-binary",
    "Pygments",
    "pypdf",
    "pytz",
    "reportlab",
    "simplejson",
    "static3",
    "svg2rlg",
    "whitenoise",
    "sentry-sdk",
    "diff-match-patch",
    "python-barcode",
    "django-hcaptcha",
    "z3c.rml",
    "pikepdf",
    "django-queryable-properties",
    "django-mass-edit",
    "selenium",
    "zope.interface",
]

[dependency-groups]
dev = [
    "PyPOM",
    "pycodestyle",
    "coveralls",
    "django-coverage-plugin",
    "pytest-cov",
    "pytest-django",
    "pluggy",
    "pytest-splinter",
    "pytest",
    "pytest-reverse",
    "pytest-xdist[psutil]",
    "PyPOM[splinter]",
    "autopep8>=2.3.2",
    "pip-audit>=2.10.1",
]
