# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0030_auth_request_sending'),
        ('RIGS', '0026_auto_20170510_1846'),
    ]

    operations = [
    ]
