# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('RIGS', '0031_merge_20170512_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIGSVersion',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('reversion.version',),
        ),
        migrations.AlterField(
            model_name='event',
            name='collector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='collected by'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_mic', to=settings.AUTH_USER_MODEL, verbose_name='MIC'),
        ),
        migrations.AlterField(
            model_name='event',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PO'),
        ),
        migrations.AlterField(
            model_name='eventauthorisation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='authorisation amount'),
        ),
        migrations.AlterField(
            model_name='eventauthorisation',
            name='uni_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='University ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Please use ex. VAT', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('I', 'Internal'), ('E', 'External'), ('SU', 'SU Core'), ('T', 'TEC Adjustment')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
