# Generated by Django 2.0.3 on 2018-03-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0032_auto_20170904_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
