# Generated by Django 2.0.5 on 2019-07-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0033_auto_20180325_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='risk_assessment_edit_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
