# Generated by Django 2.0.13 on 2020-01-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0035_auto_20191124_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
