# Generated by Django 2.0.13 on 2020-01-11 18:29
# This migration ensures that legacy Profiles from before approvals were implemented are automatically approved
from django.db import migrations

def approve_legacy(apps, schema_editor):
    Profile = apps.get_model('RIGS', 'Profile')
    for person in Profile.objects.all():
        person.is_approved = True
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0036_profile_is_approved'),
    ]

    operations = [
        migrations.RunPython(approve_legacy, migrations.RunPython.noop)
    ]
