# Generated by Django 2.0.13 on 2020-03-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0037_approve_legacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
