# Generated by Django 2.0.13 on 2020-01-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0037_auto_20200111_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
