# Generated by Django 3.0.3 on 2020-03-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0038_auto_20200306_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCrew',
        ),
    ]
