# Generated by Django 3.0.3 on 2020-04-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0039_delete_eventcrew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RIGSVersion',
        ),
    ]
