# Generated by Django 3.1.5 on 2021-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0039_auto_20210123_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
