# Generated by Django 3.1 on 2020-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0039_auto_20200915_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchecklist',
            name='medium_event',
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='event_size',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=0),
            preserve_default=False,
        ),
    ]
