# Generated by Django 3.1 on 2020-09-29 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0040_auto_20200925_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchecklist',
            name='ear_plugs',
            field=models.BooleanField(blank=True, help_text='Ear plugs issued to crew where needed?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='earthing',
            field=models.BooleanField(blank=True, help_text='Equipment appropriately earthed?<br><small>(truss, stage, generators etc)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='RIGS.event'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='event_size',
            field=models.IntegerField(blank=True, choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='exits',
            field=models.BooleanField(blank=True, help_text='Emergency exits clear?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='extinguishers_location',
            field=models.CharField(blank=True, help_text='Location of fire extinguishers', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='hs_location',
            field=models.CharField(blank=True, help_text='Location of Safety Bag/Box', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='pat',
            field=models.BooleanField(blank=True, help_text='All equipment in PAT period?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='power_mic',
            field=models.ForeignKey(blank=True, help_text='Who is the Power MIC?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Power MIC'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='safe_packing',
            field=models.BooleanField(blank=True, help_text='Equipment packed away safely?<br><small>(including flightcases)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='safe_parking',
            field=models.BooleanField(blank=True, help_text='Vehicles parked safely?<br><small>(does not obstruct venue access)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='trip_hazard',
            field=models.BooleanField(blank=True, help_text='Appropriate barriers around kit and cabling secured?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='warning_signs',
            field=models.BooleanField(blank=True, help_text='Warning signs in place?<br><small>(strobe, smoke, power etc.)</small>'),
        ),
    ]
