# Generated by Django 3.1.13 on 2021-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0041_auto_20210302_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', max_digits=5, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='w1_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', max_digits=5, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='w2_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', max_digits=5, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='w3_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', max_digits=5, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
    ]

