# Generated by Django 3.0.7 on 2020-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0041_auto_20200528_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='area_outside_of_control',
            field=models.BooleanField(help_text="Is any part of the work area out of TEC's direct control or openly accessible during the build or breakdown period?"),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='barrier_required',
            field=models.BooleanField(help_text='Is there a requirement for TEC to provide any barrier for security or protection of persons/equipment?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='big_power',
            field=models.BooleanField(help_text='Does the event require larger power supplies than 13A or 16A single phase wall sockets, or draw more than 20A total current?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='contractors',
            field=models.BooleanField(help_text='Are you using any external contractors?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='crew_fatigue',
            field=models.BooleanField(help_text='Is crew fatigue likely to be a risk at any point during this event?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='generators',
            field=models.BooleanField(help_text='Will generators be used?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='known_venue',
            field=models.BooleanField(help_text='Is the event in a venue that you and/or TEC have experience working in?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='multiple_electrical_environments',
            field=models.BooleanField(help_text='Will the electrical installation occupy more than one electrical environment?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='noise_monitoring',
            field=models.BooleanField(help_text='Does the event require noise monitoring or any non-standard procedures in order to comply with health and safety legislation or site rules?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='nonstandard_emergency_procedure',
            field=models.BooleanField(help_text="Does the emergency procedure for the event differ from TEC's standard procedures?"),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='nonstandard_equipment',
            field=models.BooleanField(help_text="Does the event require any hired in equipment or use of equipment that is not covered by TEC's standard risk assessments and method statements?"),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='nonstandard_equipment_power',
            field=models.BooleanField(help_text='Does the power plan require the use of any power equipment (distros, dimmers, motor controllers, etc.) that does not belong to TEC?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='nonstandard_use',
            field=models.BooleanField(help_text='Are TEC using their equipment in a way that is abnormal?<br><small>i.e. Not covered by TECs standard health and safety documentation</small>'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='other_companies',
            field=models.BooleanField(help_text='Are TEC working with any other companies on site?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='other_companies_power',
            field=models.BooleanField(help_text='Will TEC be supplying power to any other companies?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='safe_loading',
            field=models.BooleanField(help_text='Is there a safe load in/out?<br><small>e.g. sufficient lighting, flat, not in a crowded area etc.</small>'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='safe_storage',
            field=models.BooleanField(help_text='Are there areas to safely store equipment?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='special_structures',
            field=models.BooleanField(help_text='Does the event require use of winch stands, motors, MPT Towers, or staging?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='suspended_structures',
            field=models.BooleanField(help_text="Are any structures (excluding projector screens and IWBs) being suspended from TEC's structures?"),
        ),
    ]
