# Generated by Django 3.1.7 on 2021-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0041_auto_20210208_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
