# Generated by Django 3.1.2 on 2020-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0041_auto_20200929_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='supervisor_consulted',
            field=models.BooleanField(null=True),
        ),
    ]
