# Generated by Django 3.1.2 on 2020-10-10 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0042_riskassessment_supervisor_consulted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RIGS.venue'),
            preserve_default=False,
        ),
    ]
