# Generated by Django 3.1.13 on 2021-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0042_auto_20211007_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='initials',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
