# Generated by Django 3.0.7 on 2020-08-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0042_auto_20200703_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
