# Generated by Django 3.1.2 on 2020-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0043_auto_20201010_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='known_venue',
            field=models.BooleanField(help_text='Is this venue new to you (the MIC) or new to TEC?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='safe_loading',
            field=models.BooleanField(help_text='Are there any issues preventing a safe load in or out? (e.g. sufficient lighting, flat, not in a crowded area etc.)'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='safe_storage',
            field=models.BooleanField(help_text='Are there any problems with safe and secure equipment storage?'),
        ),
    ]
