# Generated by Django 3.0.7 on 2020-08-14 15:28

import RIGS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0043_auto_20200805_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles', models.TextField(help_text='List vehicles and their drivers')),
                ('safe_parking', models.BooleanField(help_text='Vehicles parked safely?<small>(does not obstruct venue access)</small>')),
                ('safe_packing', models.BooleanField(help_text='Equipment packed away safely?<small>(including flightcases)</small>')),
                ('exits', models.BooleanField(help_text='Emergency exits clear?')),
                ('trip_hazard', models.BooleanField(help_text='Appropriate barriers around kit and cabling secured?')),
                ('warning_signs', models.BooleanField(help_text='Warning signs in place?<small>(strobe, smoke, power etc.)</small>')),
                ('ear_plugs', models.BooleanField(help_text='Ear plugs issued to crew where needed?')),
                ('hs_location', models.TextField(help_text='Location of Safety Bag/Box')),
                ('extinguishers_location', models.TextField(help_text='Location of fire extinguishers')),
                ('rcds', models.BooleanField(help_text='RCDs installed where needed and tested?')),
                ('supply_test', models.BooleanField(help_text='Electrical supplies tested?<small>(using socket tester)</small>')),
                ('earthing', models.BooleanField(help_text='Equipment appropriately earthed?<small>(truss, stage, etc)</small>')),
                ('pat', models.BooleanField(help_text='All equipment in PAT period?')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RIGS.Event')),
                ('power_mic', models.ForeignKey(blank=True, help_text='Who is the Power MIC?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to=settings.AUTH_USER_MODEL, verbose_name='Power MIC')),
            ],
            bases=(models.Model, RIGS.models.RevisionMixin),
        ),
    ]
