# Generated by Django 3.2.11 on 2022-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0043_auto_20211027_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
