# Generated by Django 3.1.2 on 2020-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0044_auto_20201024_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='outside',
            field=models.BooleanField(default=False, help_text='Is the event outdoors?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='contractors',
            field=models.BooleanField(help_text='Are you using any external contractors?<small>i.e. Freelancers/Crewing Companies</small>'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='nonstandard_equipment',
            field=models.BooleanField(help_text="Does the event require any hired in equipment or use of equipment that is not covered by <a href='https://nottinghamtec.sharepoint.com/:f:/g/HealthAndSafety/Eo4xED_DrqFFsfYIjKzMZIIB6Gm_ZfR-a8l84RnzxtBjrA?e=Bf0Haw'>TEC's standard risk assessments and method statements?</a>"),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='other_companies',
            field=models.BooleanField(help_text='Are TEC working with any other companies on site?<small>e.g. TEC is providing the lighting while another company does sound</small>'),
        ),
    ]
