# Generated by Django 3.0.7 on 2020-08-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0044_eventchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklist',
            name='medium_event',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='earthing',
            field=models.BooleanField(help_text='Equipment appropriately earthed?<br><small>(truss, stage, etc)</small>'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='extinguishers_location',
            field=models.CharField(help_text='Location of fire extinguishers', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='hs_location',
            field=models.CharField(help_text='Location of Safety Bag/Box', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='safe_packing',
            field=models.BooleanField(help_text='Equipment packed away safely?<br><small>(including flightcases)</small>'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='safe_parking',
            field=models.BooleanField(help_text='Vehicles parked safely?<br><small>(does not obstruct venue access)</small>'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='supply_test',
            field=models.BooleanField(help_text='Electrical supplies tested?<br><small>(using socket tester)</small>'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='warning_signs',
            field=models.BooleanField(help_text='Warning signs in place?<br><small>(strobe, smoke, power etc.)</small>'),
        ),
    ]
