# Generated by Django 3.2.16 on 2022-10-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0045_subhire'),
    ]

    operations = [
        migrations.AddField(
            model_name='subhire',
            name='events',
            field=models.ManyToManyField(to='RIGS.Event'),
        ),
    ]
