# Generated by Django 3.1.2 on 2020-12-13 16:25

import RIGS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0045_auto_20201116_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='power_plan',
            field=models.URLField(blank=True, help_text="Upload your power plan to the <a href='https://nottinghamtec.sharepoint.com/'>Sharepoint</a> and submit a link", null=True, validators=[RIGS.models.validate_url]),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='rigging_plan',
            field=models.URLField(blank=True, help_text="Upload your rigging plan to the <a href='https://nottinghamtec.sharepoint.com/'>Sharepoint</a> and submit a link", null=True, validators=[RIGS.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='contractors',
            field=models.BooleanField(help_text='Are you using any external contractors?<br><small>i.e. Freelancers/Crewing Companies</small>'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='other_companies',
            field=models.BooleanField(help_text='Are TEC working with any other companies on site?<br><small>e.g. TEC is providing the lighting while another company does sound</small>'),
        ),
    ]
