# Generated by Django 3.1.2 on 2020-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0046_auto_20201213_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchecklist',
            name='event_size',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='event_size',
            field=models.IntegerField(blank=True, choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], null=True),
        ),
    ]
