# Generated by Django 3.2.16 on 2023-05-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0046_create_powertests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchecklist',
            name='all_rcds_tested',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='earthing',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_phase_rotation',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_pssc',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l1',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l2',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l3',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='labelling',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='public_sockets_tested',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='rcds',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='source_rcd',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='supply_test',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_voltage',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_voltage',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_voltage',
        ),
    ]
