# Generated by Django 3.2.16 on 2022-12-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0046_subhire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subhire',
            options={'permissions': [('subhire_finance', 'Can see financial data for subhire - insurance values')]},
        ),
    ]
