# Generated by Django 3.2.19 on 2023-05-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0047_auto_20230517_0944'),
    ]

    operations = [
                migrations.RemoveField(
            model_name='eventchecklistvehicle',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='eventchecklistvehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='all_rcds_tested',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='earthing',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_phase_rotation',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_pssc',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l1',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l2',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='fd_voltage_l3',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='labelling',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='power_mic',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='public_sockets_tested',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='rcds',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='source_rcd',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='supply_test',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w1_voltage',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w2_voltage',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_description',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_earth_fault',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_polarity',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='w3_voltage',
        ),
        migrations.AddField(
            model_name='powertestrecord',
            name='power_mic',
            field=models.ForeignKey(blank=True, help_text='Who is the Power MIC?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Power MIC'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powertestrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventChecklistCrew',
        ),
        migrations.DeleteModel(
            name='EventChecklistVehicle',
        ),
    ]
