# Generated by Django 3.2.18 on 2023-05-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0047_auto_20230508_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchecklistvehicle',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='eventchecklistvehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='eventchecklist',
            name='power_mic',
        ),
        migrations.AddField(
            model_name='powertestrecord',
            name='power_mic',
            field=models.ForeignKey(blank=True, help_text='Who is the Power MIC?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Power MIC'),
        ),
        migrations.DeleteModel(
            name='EventChecklistCrew',
        ),
        migrations.DeleteModel(
            name='EventChecklistVehicle',
        ),
    ]
