# Generated by Django 3.1 on 2020-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0048_auto_20200829_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklist',
            name='all_rcds_tested',
            field=models.BooleanField(default=False, help_text='All circuit RCDs tested?<small>(using test button)</small>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_earth_fault',
            field=models.IntegerField(default=False, help_text='Earth Fault Loop Impedance (Z<small>S</small>)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_phase_rotation',
            field=models.BooleanField(default=False, help_text='Phase Rotation<br><small>(if required)</small>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_pssc',
            field=models.IntegerField(default=False, help_text='Prospective Short Circuit Current'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_voltage_l1',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_voltage_l2',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='fd_voltage_l3',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='labelling',
            field=models.BooleanField(default=False, help_text='Appropriate and clear labelling on distribution and cabling?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='public_sockets_tested',
            field=models.BooleanField(default=False, help_text='Public/Performer accessible circuits tested?<small>(using socket tester)</small>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='source_rcd',
            field=models.BooleanField(default=False, help_text='Source RCD protected?<br><small>(if cable is more than 3m long) </small>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='earthing',
            field=models.BooleanField(help_text='Equipment appropriately earthed?<br><small>(truss, stage, generators etc)</small>'),
        ),
    ]
