# Generated by Django 3.2.18 on 2023-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0049_auto_20230529_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='forum_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
