# Generated by Django 3.2.19 on 2023-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0049_auto_20230520_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powertestrecord',
            name='fd_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>) / Ω', max_digits=6, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='powertestrecord',
            name='w1_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>) / Ω', max_digits=6, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='powertestrecord',
            name='w2_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>) / Ω', max_digits=6, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='powertestrecord',
            name='w3_earth_fault',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earth Fault Loop Impedance (Z<small>S</small>) / Ω', max_digits=6, null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
    ]
