# Generated by Django 3.1 on 2020-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0049_auto_20200829_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_earth_fault',
            field=models.IntegerField(help_text='Earth Fault Loop Impedance (Z<small>S</small>)', verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_phase_rotation',
            field=models.BooleanField(help_text='Phase Rotation<br><small>(if required)</small>', verbose_name='Phase Rotation'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_pssc',
            field=models.IntegerField(help_text='Prospective Short Circuit Current', verbose_name='PSCC'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l1',
            field=models.IntegerField(help_text='L1 - N', verbose_name='First Distro Voltage L1-N'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l2',
            field=models.IntegerField(help_text='L2 - N', verbose_name='First Distro Voltage L2-N'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l3',
            field=models.IntegerField(help_text='L3 - N', verbose_name='First Distro Voltage L3-N'),
        ),
    ]
