# Generated by Django 3.2.19 on 2023-07-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0050_event_forum_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('I', 'Internal'), ('E', 'External'), ('T', 'TEC Adjustment')], default='', max_length=2),
        ),
    ]
