# Generated by Django 3.2.19 on 2023-06-27 10:31

import RIGS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0050_event_forum_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='forum_url',
            field=models.URLField(blank=True, null=True, validators=[RIGS.models.validate_forum_url]),
        ),
    ]
