# Generated by Django 3.1 on 2020-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0051_auto_20200830_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchecklist',
            name='all_rcds_tested',
            field=models.BooleanField(blank=True, help_text='All circuit RCDs tested?<small>(using test button)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_earth_fault',
            field=models.IntegerField(blank=True, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', null=True, verbose_name='Earth Fault Loop Impedance'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_phase_rotation',
            field=models.BooleanField(blank=True, help_text='Phase Rotation<br><small>(if required)</small>', null=True, verbose_name='Phase Rotation'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_pssc',
            field=models.IntegerField(blank=True, help_text='Prospective Short Circuit Current', null=True, verbose_name='PSCC'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l1',
            field=models.IntegerField(blank=True, help_text='L1 - N', null=True, verbose_name='First Distro Voltage L1-N'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l2',
            field=models.IntegerField(blank=True, help_text='L2 - N', null=True, verbose_name='First Distro Voltage L2-N'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='fd_voltage_l3',
            field=models.IntegerField(blank=True, help_text='L3 - N', null=True, verbose_name='First Distro Voltage L3-N'),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='labelling',
            field=models.BooleanField(blank=True, help_text='Appropriate and clear labelling on distribution and cabling?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='public_sockets_tested',
            field=models.BooleanField(blank=True, help_text='Public/Performer accessible circuits tested?<small>(using socket tester)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='rcds',
            field=models.BooleanField(blank=True, help_text='RCDs installed where needed and tested?', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='source_rcd',
            field=models.BooleanField(blank=True, help_text='Source RCD protected?<br><small>(if cable is more than 3m long) </small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='supply_test',
            field=models.BooleanField(blank=True, help_text='Electrical supplies tested?<br><small>(using socket tester)</small>', null=True),
        ),
    ]
