# Generated by Django 3.2.21 on 2023-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0051_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='on_campus',
            field=models.BooleanField(default=False, verbose_name='Is this venue on a UoN campus?'),
        ),
    ]
