# Generated by Django 3.2.25 on 2024-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0051_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parking_and_access',
            field=models.BooleanField(default=False),
        ),
    ]
