# Generated by Django 3.1 on 2020-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0052_auto_20200830_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklist',
            name='w1_description',
            field=models.CharField(blank=True, help_text='Description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w1_earth_fault',
            field=models.IntegerField(blank=True, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w1_polarity',
            field=models.BooleanField(blank=True, help_text='Polarity Checked?', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w1_voltage',
            field=models.IntegerField(blank=True, help_text='Voltage', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w2_description',
            field=models.CharField(blank=True, help_text='Description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w2_earth_fault',
            field=models.IntegerField(blank=True, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w2_polarity',
            field=models.BooleanField(blank=True, help_text='Polarity Checked?', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w2_voltage',
            field=models.IntegerField(blank=True, help_text='Voltage', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w3_description',
            field=models.CharField(blank=True, help_text='Description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w3_earth_fault',
            field=models.IntegerField(blank=True, help_text='Earth Fault Loop Impedance (Z<small>S</small>)', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w3_polarity',
            field=models.BooleanField(blank=True, help_text='Polarity Checked?', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='w3_voltage',
            field=models.IntegerField(blank=True, help_text='Voltage', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='all_rcds_tested',
            field=models.BooleanField(blank=True, help_text='All circuit RCDs tested?<br><small>(using test button)</small>', null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklist',
            name='public_sockets_tested',
            field=models.BooleanField(blank=True, help_text='Public/Performer accessible circuits tested?<br><small>(using socket tester)</small>', null=True),
        ),
    ]
