# Generated by Django 3.2.25 on 2024-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0052_event_parking_and_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='parking_and_access',
            field=models.BooleanField(default=False, help_text='Are there additional requirements for parking and access to the venue? (i.e. campus parking permits, event access wristbands)'),
            preserve_default=False,
        ),
    ]
