# Generated by Django 3.1 on 2020-08-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0053_auto_20200830_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventchecklist',
            options={'ordering': ['event'], 'permissions': [('eventchecklist_review', 'Can review ECs')]},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['event'], 'permissions': [('riskassessment_review', 'Can review RAs')]},
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
