# Generated by Django 3.1 on 2020-09-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0054_auto_20200831_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventchecklist',
            options={'ordering': ['event'], 'permissions': [('review_eventchecklist', 'Can review Event Checklists')]},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['event'], 'permissions': [('review_riskassessment', 'Can review Risk Assessments')]},
        ),
    ]
