# Generated by Django 2.0.2 on 2018-03-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180301_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Collection'),
        ),
    ]
