# Generated by Django 2.1.5 on 2019-01-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180728_1451_squashed_0021_auto_20190105_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_parent', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_parent', to='assets.Cable'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='voltage_rating',
            field=models.IntegerField(help_text='Volts'),
        ),
    ]
