# Generated by Django 2.0.13 on 2019-10-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assets', '0007_auto_20190108_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='cable',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='length',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='date_sold',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='is_cable',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='next_sched_maint',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='purchased_from',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='salvage_value',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assets.asset_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='cable',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
            preserve_default=False,
        ),
    ]
