# Generated by Django 2.0.13 on 2020-01-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('assets', '0009_auto_20200102_1933'), ('assets', '0010_assetstatus_display_class'), ('assets', '0011_auto_20200102_2040')]

    dependencies = [
        ('assets', '0008_auto_20191206_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'ordering': ['name'], 'verbose_name': 'Asset Status', 'verbose_name_plural': 'Asset Statuses'},
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='display_class',
            field=models.CharField(help_text='HTML class to be appended to alter display of assets with this status, such as in the list.', max_length=80),
        ),
    ]
