# Generated by Django 2.0.13 on 2019-10-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20191002_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
