# Generated by Django 2.0.13 on 2019-10-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20191008_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('asset_finance', 'Can see financial data for assets'),)},
        ),
    ]
