# Generated by Django 2.0.13 on 2020-02-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200103_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': (('view_supplier', 'Can view a supplier'),)},
        ),
    ]
