# Generated by Django 2.0.13 on 2020-01-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200102_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatus',
            name='display_class',
            field=models.TextField(default='', help_text='HTML class to be appended to alter display of assets with this status, such as in the list.'),
        ),
    ]
