# Generated by Django 2.0.13 on 2019-10-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20191008_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='plug',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='socket',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='asset',
            name='circuits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='csa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm^2', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='m', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='plug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to='assets.Connector'),
        ),
        migrations.AddField(
            model_name='asset',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socket', to='assets.Connector'),
        ),
        migrations.DeleteModel(
            name='Cable',
        ),
    ]
