# Generated by Django 2.0.13 on 2020-01-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200102_1933_squashed_0011_auto_20200102_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.Supplier'),
        ),
    ]
