# Generated by Django 2.0.13 on 2020-02-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20200219_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuits', models.IntegerField(blank=True, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('plug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to='assets.Connector')),
                ('socket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socket', to='assets.Connector')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='cable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.CableType'),
        ),
    ]
