# Generated by Django 2.0.13 on 2020-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20200207_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
