# Generated by Django 2.0.13 on 2020-02-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('assets', '0011_auto_20200208_2304'), ('assets', '0012_auto_20200218_1601')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0010_auto_20200207_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='csa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm²', max_digits=10, null=True),
        ),
    ]
