# Generated by Django 2.0.13 on 2019-10-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20191013_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='plug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to='assets.Connector'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='socket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socket', to='assets.Connector'),
        ),
    ]
