# Generated by Django 3.0.3 on 2020-03-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20200317_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='next_sched_maint',
        ),
    ]
