# Generated by Django 2.0.13 on 2019-10-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20191013_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('asset_finance', 'Can see financial data for assets'),)},
        ),
    ]
