# Generated by Django 2.0.13 on 2019-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20191014_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_id'], 'permissions': (('asset_finance', 'Can see financial data for assets'),)},
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='should_show',
            field=models.BooleanField(default=True, help_text='Should this be shown by default in the asset list.'),
        ),
    ]
