# Generated by Django 2.0.13 on 2020-02-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20200218_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='circuits',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='plug',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='socket',
        ),
    ]
