# Generated by Django 2.0.13 on 2019-10-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20191016_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_id'], 'permissions': (('asset_finance', 'Can see financial data for assets'), ('view_asset', 'Can view an asset'))},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': (('view_supplier', 'Can view a supplier'),)},
        ),
    ]
