# Generated by Django 2.0.13 on 2020-02-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20200218_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabletype',
            options={'ordering': ['plug', 'socket', '-circuits']},
        ),
    ]
