# Generated by Django 3.0.3 on 2020-04-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20200218_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='next_sched_maint',
        ),
    ]
