# Generated by Django 3.0.3 on 2020-04-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_remove_asset_next_sched_maint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabletype',
            name='circuits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='cores',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='plug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plug', to='assets.Connector'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socket', to='assets.Connector'),
        ),
    ]
