# Generated by Django 3.0.3 on 2020-04-13 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0016_auto_20200413_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='csa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm²', max_digits=10, null=True),
        ),
    ]
