# Generated by Django 3.2.12 on 2022-02-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_alter_cabletype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.supplier'),
        ),
    ]
