# Generated by Django 3.2.12 on 2022-02-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_asset_purchased_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
