# Generated by Django 3.2.12 on 2022-05-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_asset_salvage_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='salvage_value',
            new_name='replacement_cost',
        ),
    ]
