# Generated by Django 3.2.12 on 2022-05-26 15:23

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_rename_salvage_value_asset_replacement_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[assets.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='replacement_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[assets.models.validate_positive]),
        ),
    ]
