# Generated by Django 3.2.16 on 2022-12-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_auto_20220526_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='nickname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
