# Generated by Django 3.2.19 on 2023-05-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_asset_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=10, null=True),
        ),
    ]
