# Generated by Django 5.2.17 on 2026-10-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_asset_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cabletype',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cabletype',
            constraint=models.UniqueConstraint(fields=('plug', 'socket', 'circuits', 'cores'), name='unique_plug_socket_circuits_cores'),
        ),
    ]
