# Generated by Django 3.2.11 on 2022-01-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglevel',
            options={'ordering': ['department', 'level']},
        ),
    ]
