# Generated by Django 3.1.5 on 2021-07-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcategory',
            options={'verbose_name_plural': 'Training Categories'},
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='prerequisite_levels',
            field=models.ManyToManyField(blank=True, related_name='prerequisites', to='training.TrainingLevel'),
        ),
        migrations.AlterField(
            model_name='traininglevel',
            name='department',
            field=models.IntegerField(choices=[(0, 'Sound'), (1, 'Lighting'), (2, 'Power'), (3, 'Rigging'), (4, 'Haulage')], null=True),
        ),
        migrations.CreateModel(
            name='TrainingLevelRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(verbose_name=((0, 'Training Started'), (1, 'Training Complete'), (2, 'Passed Out')))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.trainingitem')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requirements', to='training.traininglevel')),
            ],
        ),
    ]
