# Generated by Django 3.1.5 on 2021-07-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20210706_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='confirmer', to='training.trainee'),
        ),
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='confirmed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
