# Generated by Django 3.1.5 on 2021-06-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20210630_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingcategory',
            old_name='number',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='trainingitem',
            old_name='number',
            new_name='reference_number',
        ),
    ]
