# Generated by Django 3.1.7 on 2021-08-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20210716_0150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingitemqualification',
            unique_together={('trainee', 'item', 'depth')},
        ),
        migrations.AlterUniqueTogether(
            name='traininglevelqualification',
            unique_together={('trainee', 'level')},
        ),
    ]
