# Generated by Django 3.2.12 on 2022-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_rename_name_trainingitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcategory',
            options={'ordering': ['reference_number'], 'verbose_name_plural': 'Training Categories'},
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='training.TrainingItem'),
        ),
    ]
