# Generated by Django 3.1.7 on 2021-08-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20210819_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininglevelrequirement',
            unique_together={('level', 'item')},
        ),
    ]
