# Generated by Django 3.1.7 on 2021-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210819_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglevel',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traininglevelrequirement',
            name='depth',
            field=models.IntegerField(choices=[(0, 'Training Started'), (1, 'Training Complete'), (2, 'Passed Out')]),
        ),
    ]
