# Generated by Django 3.2.18 on 2023-02-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20220223_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingitem',
            old_name='description',
            new_name='name',
        ),
    ]
