# Generated by Django 3.1.13 on 2021-09-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210903_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingitem',
            options={'ordering': ['category__reference_number', 'reference_number']},
        ),
        migrations.AlterUniqueTogether(
            name='trainingitem',
            unique_together={('reference_number', 'name', 'category')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='trainingitemqualification',
            order_with_respect_to='item',
        ),
    ]
