# Generated by Django 3.2.18 on 2023-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_rename_description_trainingitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
