# Generated by Django 3.1.13 on 2021-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210908_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
