# Generated by Django 5.2.17 on 2026-10-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_trainingitem_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingitemqualification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='traininglevelqualification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='traininglevelrequirement',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='trainingitem',
            constraint=models.UniqueConstraint(fields=('reference_number', 'active', 'category'), name='unique_reference_number_active_category'),
        ),
        migrations.AddConstraint(
            model_name='trainingitemqualification',
            constraint=models.UniqueConstraint(fields=('trainee', 'item', 'depth'), name='unique_trainee_item_depth'),
        ),
        migrations.AddConstraint(
            model_name='traininglevelqualification',
            constraint=models.UniqueConstraint(fields=('trainee', 'level'), name='unique_trainee_level'),
        ),
        migrations.AddConstraint(
            model_name='traininglevelrequirement',
            constraint=models.UniqueConstraint(fields=('level', 'item'), name='unique_level_item'),
        ),
    ]
