# Generated by Django 5.2.17 on 2026-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='technician_can_train',
            field=models.BooleanField(default=False, help_text="Technicians in this item's department who are passed out on it may deliver training up to Training Complete"),
        ),
    ]
