# Generated by Django 3.1.13 on 2021-12-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20211221_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcategory',
            name='reference_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainingitem',
            name='reference_number',
            field=models.IntegerField(),
        ),
    ]
