# Generated by Django 5.2.17 on 2026-10-03 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_trainingitem_technician_can_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcategory',
            name='training_level',
            field=models.ForeignKey(blank=True, help_text='If this is set, technicians must hold this level (e.g. Sound Technician) to deliver training in technician-trainable items in this category. If not set, any technician may.', null=True, on_delete=django.db.models.deletion.CASCADE, to='training.traininglevel'),
        ),
    ]
