# Generated by Django 3.1.13 on 2022-01-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20211228_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglevelqualification',
            options={'ordering': ['-confirmed_on']},
        ),
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='level_qualifications', to='training.trainee'),
        ),
    ]
