# Generated by Django 3.2.11 on 2022-01-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20220102_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.trainingcategory'),
        ),
        migrations.AlterField(
            model_name='trainingitemqualification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingitem'),
        ),
        migrations.AlterField(
            model_name='trainingitemqualification',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications_granted', to='training.trainee'),
        ),
        migrations.AlterField(
            model_name='trainingitemqualification',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications_obtained', to='training.trainee'),
        ),
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmer', to='training.trainee'),
        ),
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.traininglevel'),
        ),
        migrations.AlterField(
            model_name='traininglevelqualification',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_qualifications', to='training.trainee'),
        ),
        migrations.AlterField(
            model_name='traininglevelrequirement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingitem'),
        ),
        migrations.AlterField(
            model_name='traininglevelrequirement',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='training.traininglevel'),
        ),
    ]
